spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak-admin-client  # Replace with your client ID
            client-secret: EqCifnC9y3YRM9u2JqToBRnZqaH7al8J  # Replace with your client secret
            authorization-grant-type: client_credentials
            scope: openid
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master  # Keycloak realm issuer URI
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
  cloud:
    gateway:
      routes:
        #Normal Config
        - id: keycloak-admin-client
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/api/v1/group/** , /api/v1/user/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer {token}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/v1/task/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, Bearer {token}
        
        #Configure Swagger With Gateway
        - id: keycloak-admin-client-swagger
          uri: lb://keycloak-admin-client
          predicates:
            - Path=/v3/api-docs/keycloak-admin-client
          filters:
            - RewritePath=/v3/api-docs/keycloak-admin-client,/v3/api-docs
        - id: task-service-swagger
          uri: lb://task-service
          predicates:
            - Path=/v3/api-docs/task-service
          filters:
            - RewritePath=/v3/api-docs/task-service,/v3/api-docs
server:
  port: 9090
#Swagger UI Config
springdoc:
  swagger-ui:
    oauth:
      client-id: keycloak-admin-client        # Your client ID for Keycloak
      client-secret: EqCifnC9y3YRM9u2JqToBRnZqaH7al8J  # Your client secret for Keycloak
      authorization-url: http://localhost:8080/realms/master/protocol/openid-connect/auth  # Keycloak auth URL
      token-url: http://localhost:8080/realms/master/protocol/openid-connect/token  # Keycloak token endpoint
      scopes: openid                          # Scopes you want to request
    path: /swagger-ui/index.html
  oauth2:
    client-credentials-flow:
      client-id: keycloak-admin-client        # Your client ID
      client-secret: EqCifnC9y3YRM9u2JqToBRnZqaH7al8J  # Your client secret
      token-url: http://localhost:8080/realms/master/protocol/openid-connect/token  # Keycloak token endpoint
#Register into Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true